sudo: false

language: node_js
node_js:
  - "8"
  - "10"
  - node

cache:
  directories:
    $HOME/.npm

before_install:
  # prevent the npm loading indicator
  - npm config --global set spin false
  # For tests that use git
  - git config --global user.email "tests@npm.org"
  - git config --global user.name "Travis"

install:
  - npm install --no-optional

script: npm test